name: "Publish"
permissions:
  contents: write  

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/publish_pypi/**'

jobs:

  bump_and_publish:
    name: Bump version and publish package
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Bump API version
        run: uv version --bump patch
      - name: Commit and push new version
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}"@users.noreply.github.com
          git checkout -b main
          git add pyproject.toml
          git commit -m "Bump API version"
          git push --force-with-lease
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Build package
        run: uv build
      - name: Publish package
        run: uv publish --publish-url https://test.pypi.org/legacy